"""empty message

Revision ID: d6ffbcc6ea67
Revises: 
Create Date: 2017-07-19 00:05:00.382341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ffbcc6ea67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256, convert_unicode=True), nullable=False),
    sa.Column('email', sa.String(length=256, convert_unicode=True), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('user_emails', 'profiles', ['email'], unique=True)
    op.create_index('usernames', 'profiles', ['username'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256, convert_unicode=True), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_index('usernames', table_name='profiles')
    op.drop_index('user_emails', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
